First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Controllers/API/EmployeeController.cs
using FVGen3.BusinessLogic.Interfaces;
using FVGen3.Domain.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Hosting;
using System.Web.Http;
using FVGen3.Common;
using FVGen3.DataLayer.DTO;
using Newtonsoft.Json;
using FVGen3.WebUI.Models;

namespace FVGen3.WebUI.Controllers.API
{
    public class EmployeeController : ApiController
    {
        private IEmployeeBusiness _employee;
        IOrganizationBusiness _org;
        public EmployeeController(IEmployeeBusiness _employee,IOrganizationBusiness _org)

        {
            this._employee = _employee;
            this._org = _org;
        }
        [HttpPost]
        public object Trainings()
        {
            var clientSecret = "";
            try
            {
                clientSecret = Request.Headers.GetValues("ClientSecret").FirstOrDefault();
                var orgId = _org.GetOrganization(clientSecret).OrganizationID;
                return _employee.VendorEmployeeTrainings(orgId);
            }
            catch(Exception ee)
            {
                ExceptionModel ExceptionModel = new ExceptionModel();
                ExceptionModel.Message = "Unable to preocess the request,Please try again with valid client secret.";
                ExceptionModel.ExceptionMessage = ee.Message;                
            }
            return "";
        }

        [HttpPost]
        public string SinePro([FromBody] SignProCheckin param)
        {
            var path = "c:\\sinepro\\"+ DateTime.Now.ToString("yyyy MMMM dd HHmmss") + ".csv";
            try
            {
                var checkInCheckout = new SineProCheckinCheckout
                {
                    RecId = param.data.id,
                    LastName = param.data.lastName,
                    FirstName = param.data.firstName,
                    EmployeeEmail = param.data.email,
                    MobileNo = param.data.mobile,
                    ExpiryDate = param.data.expiresDate,
                    VisitorType = param.data.visitorType?.name,
                    VisitorId = param.data.visitorType?.id,
                    CompanyName = param.data.company,
                    SiteName = param.data.site?.name,
                    SiteId = param.data.site?.id,
                    Status = param.data.status,
                    ClientId = 13159
                };
                if (param.event_ == "signin_after")
                {
                    checkInCheckout.CheckinTime = param.data.startDate;
                    checkInCheckout.CheckinUser = param.data.host?.lastName + ", " + param.data.host?.firstName;
                }
                else
                {
                    checkInCheckout.CheckOutUser = param.data.host?.lastName + ", " + param.data.host?.firstName;
                    checkInCheckout.CheckoutTime = param.data.expiresDate;
                }

                checkInCheckout.HostId = param.data.host?.id;
                checkInCheckout.HostGroupId = param.data.host?.hostGroup;
                checkInCheckout.HostGroupName = param.data.host?.hostGroupName;
                _employee.SaveSignProCheckinCheckOut(checkInCheckout);
            }
            catch (Exception e)
            {
                //SendMail.sendMail("rajesh.pendela@ahaapps.com", e.Message + e.StackTrace, "Sine Pro Crash");
            }

            File.WriteAllText(path , JsonConvert.SerializeObject(param));
            return "Triggered Successfully";
        }
    }
}

First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Controllers/PrequalificationController.cs
/*
Page Created Date:  28/05/2013
Created By: Rajesh Pendela
Purpose:All operations of prequalification will be controlled here
Version: 1.0
****************************************************
Version: 2.0
Date: 07/25/2013
Changes by : Rajesh Pendela
Changes: Pop up view of Dynamic subsection for Prequalification sites
*****************************************************
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FVGen3.WebUI.Annotations;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Configuration;
using System.IO;
using FVGen3.WebUI.Utilities;
using System.Net.Mail;
using iTextSharp.text.pdf;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using FVGen3.BusinessLogic;
using AhaApps.Libraries.Extensions;
using FVGen3.BusinessLogic.Interfaces;
using FVGen3.WebUI.Constants;
using FVGen3.WebUI.Models;
using Resources;
using PayPal.Sample;
using PayPal.Sample.Utilities;
using FVGen3.BusinessLogic.Extentions;
using FVGen3.DataLayer.DTO;
using System.Web.Script.Serialization;
using FVGen3.Domain.Concrete;
using FVGen3.Domain.Entities;
using FVGen3.Domain.ViewModels;
using FVGen3.Domain.LocalModels;

namespace FVGen3.WebUI.Controllers
{
    public class PrequalificationController : BaseController
    {

        //
        // GET: /Prequalification/
        EFDbContext entityDB;
        private IPrequalificationBusiness _prequalification;
        private ITemplateToolBusiness _templateToolBusiness;
        private IOrganizationBusiness _organization;
        private IClientBusiness _clientBusiness;
        private IPrequalificationSitesBusiness _pqSites;
        private IDocumentBusiness _documents;
        private ISystemUserBusiness _sysUser;
        private IEmailTemplateBusiness _email;
        private IEmployeeBusiness _employee;
        private RequestFlow flow = new RequestFlow();
        private PrequalificationHelper helper = new PrequalificationHelper();
        public PrequalificationController(IDocumentBusiness _documents, IPrequalificationSitesBusiness _pqSites, ISystemUserBusiness _sysUser, IClientBusiness clientBusiness, ITemplateToolBusiness templateToolBusiness, IPrequalificationBusiness _prequalification, IOrganizationBusiness organization, IEmailTemplateBusiness email, IEmployeeBusiness employee)
        {
            entityDB = new EFDbContext();
            this._prequalification = _prequalification;
            _templateToolBusiness = templateToolBusiness;
            _organization = organization;
            _clientBusiness = clientBusiness;
            this._pqSites = _pqSites;
            this._documents = _documents;
            this._sysUser = _sysUser;
            _email = email; var a = new List<long>();
            _employee = employee;
        }

        [SessionExpire(lastPageUrl = "../SystemUsers/Dashboard")]
        [HeaderAndSidebar(isPermissionRequired = true, headerName = "PREQUALIFICATIONREQUIREMENTS", sideMenuName = "", ViewName = "TemplatesList")]
        public ActionResult TemplatesList(long PreQualificationId, long? oldPreQualificationId, Guid? templateId)//Rajesh on 9/21/2013
        {

            if (PreQualificationId == -1)//Means He clicked Renewal
            {
                //PreQualificationId = AddNewPrequalification(PreQualificationId);
                //Rajesh on 9/21/2013
                long tempPreQualificationId = AddNewPrequalification(oldPreQualificationId);
                if (tempPreQualificationId != -1)
                    PreQualificationId = tempPreQualificationId;
                //Ends<<<
                else
                {
                    var oldPrequalification = entityDB.Prequalification.Find(oldPreQualificationId);
                    var latestPrequalification = entityDB.LatestPrequalification.FirstOrDefault(rec => rec.VendorId == oldPrequalification.VendorId && rec.ClientId == oldPrequalification.ClientId);

                    return
                 Redirect("../Prequalification/TemplateSectionsList?templateId=" +
                          latestPrequalification.ClientTemplates.TemplateID +
                          "&TemplateSectionID=-1&PreQualificationId=" + latestPrequalification.PrequalificationId);
                }

                //To add Prequalification Logs
                Prequalification preQualificationDetails_loc = entityDB.Prequalification.Find(PreQualificationId);
                PrequalificationStatusChangeLog preQualificationLog = new PrequalificationStatusChangeLog();
                preQualificationLog.PrequalificationId = PreQualificationId;
                preQualificationLog.PrequalificationStatusId = 15;
                preQualificationLog.StatusChangeDate = DateTime.Now;
                preQualificationLog.StatusChangedByUser = new Guid(Session["UserId"].ToString());
                preQualificationLog.PrequalificationStart = preQualificationDetails_loc.PrequalificationStart;
                preQualificationLog.PrequalificationFinish = preQualificationDetails_loc.PrequalificationFinish;
                preQualificationLog.CreatedDate = DateTime.Now;
                entityDB.PrequalificationStatusChangeLog.Add(preQualificationLog);
                entityDB.SaveChanges();
                //>>>Ends

                entityDB = new EFDbContext();
            }
            //This session value was created for Template sections list

            Prequalification preQualificationDetails = entityDB.Prequalification.Find(PreQualificationId);

            ViewBag.CopyAnswers = (preQualificationDetails.Vendor.CopyAnswers == null) ? 0 : (int)preQualificationDetails.Vendor.CopyAnswers;

            //////////////////

            long[] prequalificationStatus = { 1, 2 };
            int status = Array.IndexOf(prequalificationStatus, preQualificationDetails.PrequalificationStatusId);

            if (status == -1 && preQualificationDetails.ClientTemplates != null)
            {
                if (preQualificationDetails.locked != null && preQualificationDetails.locked == true)
                {
                    SendUnlockRequestNotification(preQualificationDetails.PrequalificationId, preQualificationDetails);
                    return Redirect("../SystemUsers/Dashboard");
                }
                return Redirect("../Prequalification/TemplateSectionsList?templateId=" + preQualificationDetails.ClientTemplates.TemplateID + "&TemplateSectionID=-1&PreQualificationId=" + PreQualificationId);
            }



            if (preQualificationDetails.PrequalificationStatusId != 2)
            {
                //Rajesh DT:-8/7/2013>>>>
                preQualificationDetails.PrequalificationStart = DateTime.Now;
                DateTime FinishDateTime = new DateTime();
                var preStatus = entityDB.PrequalificationStatus.FirstOrDefault(rec => rec.PrequalificationStatusId == 2);
                if (preStatus != null)
                {
                    if (preStatus.PeriodLengthUnit.ToLower().Equals("d"))
                        FinishDateTime = DateTime.Now.AddDays(preStatus.PeriodLength);
                    else if (preStatus.PeriodLengthUnit.ToLower().Equals("m"))
                        FinishDateTime = DateTime.Now.AddMonths(preStatus.PeriodLength);
                    else if (preStatus.PeriodLengthUnit.ToLower().Equals("y"))
                        FinishDateTime = DateTime.Now.AddYears(preStatus.PeriodLength);
                }
                preQualificationDetails.PrequalificationFinish = FinishDateTime;
                // Ends <<<<<



                //To add Prequalification Logs
                PrequalificationStatusChangeLog preQualificationLog = new PrequalificationStatusChangeLog();
                preQualificationLog.PrequalificationId = preQualificationDetails.PrequalificationId;
                preQualificationLog.PrequalificationStatusId = 2;
                preQualificationLog.StatusChangeDate = DateTime.Now;
                preQualificationLog.StatusChangedByUser = new Guid(Session["UserId"].ToString());
                preQualificationLog.PrequalificationStart = preQualificationDetails.PrequalificationStart;
                preQualificationLog.PrequalificationFinish = preQualificationDetails.PrequalificationFinish;
                preQualificationLog.CreatedDate = DateTime.Now;
                entityDB.PrequalificationStatusChangeLog.Add(preQualificationLog);
                //>>>Ends
            }

            preQualificationDetails.PrequalificationStatusId = 2;
            ViewBag.PreQualificationId = PreQualificationId;
            entityDB.Entry(preQualificationDetails).State = EntityState.Modified;
            entityDB.SaveChanges();
            if (templateId != null)
            {

                Guid clientTemplateId = preQualificationDetails.ClientTemplateId.Value;
                var ISEriClient = entityDB.ClientTemplates.FirstOrDefault(rec => rec.TemplateID == templateId && rec.Organizations.OrganizationType == OrganizationType.SuperClient);
                if (ISEriClient != null) { clientTemplateId = ISEriClient.ClientTemplateID; }

                return Redirect("StartTemplate?ClientTemplateId=" + clientTemplateId + "&PrequalificationId=" + PreQualificationId + "");
            }
            var templatesList = entityDB.ClientTemplates.Where(records => records.ClientID == preQualificationDetails.ClientId && records.Templates.TemplateType == 0 && records.Templates.TemplateStatus == 1 && records.Templates.IsHide != true).OrderBy(rec => rec.Templates.TemplateSequence).ToList();


            if (preQualificationDetails.Client.OrganizationType != OrganizationType.SuperClient)
            {
                templatesList = templatesList.Where(r => r.Templates.IsERI != true).ToList();

            }// Kiran on 03/13/2015 to sort the templates by template name
            ViewBag.templatesList = templatesList;
            return View();
        }

First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Views/Prequalification/AgreementEmailCompose.cshtml
@{
    Layout = null;
}
@model FVGen3.Domain.Entities.LocalEmailComposeModel
           @using Resources;
<!DOCTYPE html>
@Styles.Render("~/css/appPopUp.css")
@Styles.Render("~/css/appInnerPages.css")
@Scripts.Render("~/js/jquery-1.9.1.min.js")
@Scripts.Render("~/js/common.js")
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/Content/Javascript/ckeditor/ckeditor.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/Javascript/ckeditor/adapters/jquery.js")"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $(".bodyRichText").ckeditor();
    });
</script>

@if (@ViewBag.EmailStatus ==false)
{
    <div>
        <p class="errorMessage">@Resources.Common_EmailSendingFailedMsg </p>
    </div>
}
<div class="popUpContainer">
    <div class="popUpContent">


        <div class="page-title">
            <h2> @Resources.Send_Email </h2>
        </div>

        @using (Html.BeginForm())
        {

            @Html.HiddenFor(model => model.TemplateId)
            @Html.HiddenFor(model => model.PrequalificationId)
            @Html.HiddenFor(r=>r.SubSectionId)
            @Html.HiddenFor(model => model.ToAddress)
            <div class="rowPopUp">
                <div class="emailDiv">
                    <label class="enableStar"> @Resources.Email_To</label>
                    @Model.ToAddress
                    <div class="alertText"> @Html.ValidationMessageFor(model => model.ToAddress) </div>
                </div>
                <div class="emailDiv" id="acceptVendor_Div_Id">
                    <label> @Resources.Email_Cc</label>
                    @Html.TextBoxFor(model => model.CCAddress, new { @maxlength = "250" })
                    <div class="alertText"> @Html.ValidationMessageFor(model => model.CCAddress) </div>
                </div>
            </div>
            <div class="rowPopUp">
                <label class="enableStar">@Resources.Email_Subject</label>
                @Html.TextBoxFor(model => model.Subject, new { @maxlength = "200" })
                <div class="alertStar"> @Html.ValidationMessageFor(model => model.Subject) </div>
            </div>

            <div class="rowPopUp">
                <table width="87%">
                    <tr>
                        <td valign="top"><label class="enableStarPopUp">@Resources.Email_Body</label></td>
                    </tr>
                    <tr>
                        <td>
                            <textarea id="Body" name="Body" class="bodyRichText">
                                @Html.Raw(Model.Body)
                            </textarea>
                        </td>
                    </tr>
                </table>
                <div class="alertStar"> @Html.ValidationMessageFor(model => model.Body) </div>
            </div>
           

            <div class="pageFooterContent">
                <div class="pageFooterButtons">
                    <table>
                        <tr>
                            <td><button type="submit" btntype="Insert" class="pageFooterButton">@Resources.Send_Email </button></td>
                        </tr>
                    </table>
                </div>
            </div>
        }
    </div>
</div>

First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Views/Prequalification/NotifyURLForMerchant.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Resources.Resources.Notify_Merchant</title>
</head>
<body>
    <div>
        <h2>@ViewBag.NotifyURLString</h2>
    </div>
</body>
</html>

First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Views/Prequalification/PrequalificationSites.cshtml
<!--
 *****************************************************
Page Created Date:  30/06/2013
Created By: Rajesh Pendela
Purpose: Dynamic Prequlification - Adding Prequalification Sites while answering a questionnaires
Version: 1.0
****************************************************
-->


@{
    ViewBag.Title = "Prequalification Sites";
}
@model FVGen3.Domain.Entities.LocalAddPrequalificationSite
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name="viewport" content="width=device-width"/>
@Scripts.Render("~/Scripts/jquery-1.9.1.min.js")
@Styles.Render("~/css/appPopUp.css")
@Styles.Render("~/css/appInnerPages.css")
@Scripts.Render("~/js/common.js")
@Scripts.Render("~/Scripts/Application/Common/Http.js")
@Scripts.Render("~/Scripts/Application/Control/Controls.js")
    
</head>


    @Scripts.Render("~/Scripts/jquery-1.9.1.min.js")
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script type="text/javascript">
        var flag = false;
        $(document).ready(function () {
            // Kiran on 01/09/2015
            var busUnitId = $("#BusinessUnit").val();
            
            // Ends<<<
            getClientBusinessUnits();
            if (busUnitId != null) {
                getBusinessUnitSites();
            }
            $("#BusinessUnit").change(function () {
                getBusinessUnitSites();

            });

            $("#form").submit(function (event) {
            
                var rowCount = $('.assignTemplateScrollCheckbox').find("input:checkbox:checked:not([disabled])").length;
         
                if (rowCount == 0) {
                    alert("Please select atleast one Business Unit Site");
                    return false;
                }
                else
                  
                    return true;
            });

        });

        function getClientBusinessUnits()
        {
            Post("../Prequalification/GetClientBusinessUnits",
              { clientId: $("#ClientId").val() },
              function (data) {
                  var controls = $(Controls.Dropdown(data));
                  controls.attr("id", "BusinessUnit");
                  controls.attr("name", "BusinessUnit");
                  controls.attr("onchange", "getBusinessUnitSites()");
              
                  $(controls).val(@Model.BusinessUnit);
                  $("#businessUnitsRow").html(controls);
                  getBusinessUnitSites();
              });
        }

        function getBusinessUnitSites() {
            $.ajax({
                type: 'Post',
                url: '../SystemUsers/GetClientBusUnitSites',
                data: '&busUnitId=' + $("#BusinessUnit").val() + '&prequlificationId=' + $("#preQualificationId").val(), // Mani on 04/10/2015
                success: function (data) {
                    $('#ClientBusinessUnitSiteId').empty("");
                    for (var i = 0; i < data.length; i++) {
                        var busUnitSiteId = data[i].Value;
                        var siteName = data[i].Text;
                        var isChecked = data[i].IsChecked;
                        var busUnitSites = "";
                        if (busUnitSiteId == 999) {
                            busUnitSites += "<div><input type='hidden' name='ClientBusinessUnitSites[" + i + "].BusinessUnitSiteId' value='" + busUnitSiteId + "' /><input type='checkbox' id='ClientBusinessUnitSites_" + i + "__IsChecked' name='ClientBusinessUnitSites[" + i + "].IsChecked' onclick='Checkall(this)' /><label for='ClientBusinessUnitSites_" + i + "__IsChecked'>" + siteName + "</label></div>";
                        }
                        else {
                            busUnitSites += "<div><input type='hidden' name='ClientBusinessUnitSites[" + i + "].BusinessUnitSiteId' value='" + busUnitSiteId + "' /><input type='checkbox' id='ClientBusinessUnitSites_" + i + "__IsChecked' name='ClientBusinessUnitSites[" + i + "].IsChecked' onclick='CheckboxCheckedOrNot(this)' /><label for='ClientBusinessUnitSites_" + i + "__IsChecked'>" + siteName + "</label></div>";
                        }
                            
                        $('#ClientBusinessUnitSiteId').append(busUnitSites);
                    }

                    if (flag == false) {
                        $("#ClientBusinessUnitSite").val('@Model.ClientBusinessUnitSite');
                        flag = true;
                    }

                },
                error: function () {
                    console.trace();
                    alert("An error occured while fetching sites");
                }
            });
        }

        function CheckboxCheckedOrNot(obj) {

            if ($(obj).is(":checked")) {
                $(obj).val(true);
                if ($("form :input[type='checkbox']:checked").length + 1 == $("form :input[type='checkbox']").length) {
                    $(obj).closest(".popupCheckBox").find("#ClientBusinessUnitSites_0__IsChecked").prop("checked", true);
                }
            }
            else {
                $(obj).closest(".popupCheckBox").find("#ClientBusinessUnitSites_0__IsChecked").prop("checked", false);
                $(obj).val(false);
            }
            return;
        }

        function Checkall(obj) {
           
          if ($(obj).is(":checked")) {
                $("form :input[type='checkbox']").each(function () {
                    $(this).attr("checked", true);
                    $(this).val(true);
                });
            }
            else {
                 $("form :input[type='checkbox']").each(function () {
                    $(this).attr("checked", false);
                    $(this).val(false);
                });
            }
            return;
        }
        
        
    </script>


<body>
    @using (Html.BeginForm("PrequalificationSites","Prequalification",FormMethod.Post, new { id = "form" }))
    {
          <div class="popUpContainer"> 
            <div class="popUpContent">  
             <div class="popUpSubContent">
                @if (ViewBag.isERITemplate)
                { 
                     <div class="page-title">
                         <h3 style="color:#1f83bc;">@Resources.Resources.AddClientLocationInfo</h3>
                     </div>
                }
                <div class="errorMessage" style="display:none">
                   @Resources.Resources.Check_Checkbox
                </div>

                @*<div class="errorMessage">@Html.ValidationSummary(true)</div> *@
                 
                @Html.HiddenFor(x => Model.siteId) 
                @Html.HiddenFor(x => Model.preQualificationId) 
                @Html.HiddenFor(x => Model.subSectionId)
          
                <div class="page-title"><h2>
                    @if (@ViewBag.Client == @Resources.LocalConstants.Clayco_ClientId)
                {@:@Resources.Resources.Pq_Site_Heading_for_only_clayco
                    }
                else {
                   @: @Resources.Resources.AddClientBusinessUnit_Heading
                    }
                    </h2>  
	            </div> 
                    
                 <div class="rowPopUp"
                      @if (!ViewBag.isERITemplate) { @: style="display:none;"
                                               }>
                     <table>
                         <tr>
                             <td><label>@Resources.Resources.AddOrEditCustomTemplate_label_SelectClient</label></td>
                             <td>
                                 <select id="ClientId" questionColumnId="-1"  name="ClientId" onchange="getClientBusinessUnits()">
                                     @foreach (var item in (List<KeyValuePair<string, string>>)ViewBag.clients)
                                     {
                                         <option value="@item.Key"
                                                 @if (Model.ClientId.ToString() == item.Key) { @: selected
                                                                                                      }>
                                             @item.Value
                                         </option>
                                     }
                                 </select>
                             </td>
                         </tr>
                     </table>
                 </div>

                    <div class="rowPopUp" 
                         @if (ViewBag.isERITemplate)
                            { @: style="display:none;"
                                               }>
                        <table>
                            <tr>
                                <td width="40%"><label class="enableStarPopUp">@Resources.Resources.PrequalificationSites_BussinessUnit</label></td>
                                <td width="60%" id="businessUnitsRow" > 
                                    @*@Html.DropDownListFor(x => Model.BusinessUnit, (IEnumerable<SelectListItem>)@ViewBag.BussinessUnits)
                                    <div class="alertStar">   @Html.ValidationMessageFor(x => Model.BusinessUnit)</div>*@
                                </td>
                            </tr>
                        </table>
                    </div>

                @*<div class="rowPopUp" id="ClientBusinessUnitSiteId">
                    <table>
                        <tr>
                            <td><label class="enableStarPopUp">@Resources.Resources.PrequalificationSites_BussinessUnitSite</label></td>
                            <td>
                             @if (Model.BusinessUnitSites != null)
                                 {
                                    @Html.DropDownListFor(x => Model.ClientBusinessUnitSite, (IEnumerable<SelectListItem>)Model.BusinessUnitSites)
                                 }
                                 else
                                 {
                                    @Html.DropDownListFor(x => Model.ClientBusinessUnitSite, new[] { new SelectListItem() { Text = "", Value = "" } })
                                 }
                                <div class="alertStar">   @Html.ValidationMessageFor(x => Model.ClientBusinessUnitSite)</div>
                            </td>
                        </tr>
                </table>
                  
                </div>*@
                @*<div class="rowPopUp">
                    <label>BusinessUnit Site</label>
                    <div class="assignTemplateScrollCheckbox" id="ClientBusinessUnitSiteId" style="width: 198px;height:101px;">
                    
                    </div>
                </div>*@

                <div class="rowPopUp">
                    <table>
                        <tr>
                            <td width="34%"><label>@if (@ViewBag.Client == @Resources.LocalConstants.Clayco_ClientId)
                {@:@Resources.Resources.Pq_Site_Heading_For_Clayco
                    }
                            else
                            {
                                @: @Resources.Resources.BU_Sites
                    }
                               </label></td>
                            <td width="66%">
                                <div class="assignTemplateScrollCheckbox" style="width: 256px;height:104px;">
                                    <div class="popupCheckBox" id="ClientBusinessUnitSiteId">
                                    
                                   
                                 </div>
                              </div>  
                            </td>
                        </tr>
                    </table>
                </div>

                <div class="rowPopUp">
                    <table>
                        <tr>
                            <td width="33%"><label>@Resources.Resources.Common_Label_Comments</label></td>
                            <td width="67%">
                                @Html.TextAreaFor(x => Model.Comments, new {@maxlength="400" })
                                <div class="alertStar">  @Html.ValidationMessageFor(x => Model.Comments)</div>
                            </td>
                        </tr>
                    </table>
                </div>

                <div class="pageFooterContent"> 
                    <div class="pageFooterButtons">
                        <table>
                            <tr>
                                <td><button type="submit" class="pageFooterButton">@Resources.Resources.Common_Save</button></td>
                                <td>@Resources.Resources.Common_label_or</td>
                                <td><div class="PageFooter_CancleBtn"><a href="#!" onclick="window.close();">@Resources.Resources.Common_Cancel</a></div></td>
                            </tr>	
                        </table> 
                    </div>
                </div>    

        </div>
    </div>
</div>
    }

    @*<script>
        $("#form").submit(function (e) {
            debugger;
            var HasPermission=@ViewBag.HasLocationNotificationpermission;
            var SelectedSitesCount = $("form :input[type='checkbox']:checked").length;
            if (SelectedSitesCount >= 2 && HasPermission)
            {
                alert("Please Add Selected Sites Documents");
              
            }
           
        });
    </script>*@
</body>
</html>

First  Verify WIP Build PQ Demo/WIP Build/FVGen3.WebUI/Views/Prequalification/Testing.cshtml
@{
    ViewBag.Title = "Testing";
}

<h2>Testing</h2>